name: CI

on:
  push:
    branches:
      - '*'
      - '!stable/**'
       
jobs:
  build:
    timeout-minutes: 7
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '15'
    - name: Install npm dependencies
      run: npm i
    - name: Run docker-compose
      run: docker-compose up -d
    - name: Run tests
      run: docker-compose exec -T node npm run test
